<?php

declare(strict_types=1);

namespace Iniznet\Mahout\Scaffold\Tests\E2E;

use Iniznet\Mahout\Devtools\Doctor\Checks\GatesManifestCheck;
use Iniznet\Mahout\Devtools\Doctor\Status;
use Iniznet\Mahout\Scaffold\Generator\Host;
use Iniznet\Mahout\Scaffold\Generator\Scaffold;
use Iniznet\Mahout\Scaffold\Tests\Support\StubSources;
use PHPUnit\Framework\TestCase;

/**
 * The stub trees as source code, rather than as files that get copied.
 *
 * A stub only executes once somebody generates it, so the package that carries two
 * of them can be entirely green while both are broken - which is exactly the state
 * this repository was in. Generation, tokens and drift were all gated; nothing
 * compiled what was generated, nothing resolved a reference, and the plugin tree
 * was never generated at all. These are the three cheapest gates that close that.
 *
 * The full gate run inside a generated tree stays opt-in in
 * {@see GenerationAcceptanceTest}: it takes minutes per combination and installs
 * over the network. What runs here is the part that costs no install and no
 * database, which is the part that belongs on every commit.
 */
final class StubTreeAcceptanceTest extends TestCase
{
    private string $workingDirectory;

    protected function setUp(): void
    {
        $this->workingDirectory = sys_get_temp_dir().'/mahout-stub-accept-'.uniqid();
        mkdir($this->workingDirectory, 0777, true);
    }

    protected function tearDown(): void
    {
        foreach (glob($this->workingDirectory.'/*', GLOB_ONLYDIR) ?: [] as $directory) {
            if (is_string($directory)) {
                $this->removeTree($directory);
            }
        }

        @rmdir($this->workingDirectory);
    }

    /**
     * Every reference a stub makes to the family, resolved against the family's
     * sources on disk. This is the gate that would have caught an exception naming
     * a named constructor that does not exist, in both trees, before either was
     * ever generated - the defect no other repository's gate could see because the
     * line only becomes a call inside somebody else's project.
     */
    public function testStubTreesResolveAgainstTheFamilySources(): void
    {
        $sources = StubSources::fromPackageRoot($this->packageRoot());

        if (!$sources->isAvailable()) {
            self::markTestSkipped('The sibling packages are not on disk, so an empty index would prove nothing.');
        }

        $findings = $sources->audit($sources->stubFiles($this->packageRoot()));

        self::assertSame([], $findings, "a stub calls a surface the family does not declare:\n".implode("\n", $findings));
    }

    /**
     * The gate list a starter declares is the promise every generated project
     * inherits, so a canonical gate dropped, edited or reordered in a stub is not a
     * stub's problem: it ships. The check is the family's own, run against the
     * manifest rather than against an install, which is what makes it cheap enough
     * to run on every commit.
     */
    public function testBothHostsDeclareTheGatesTheManifestOwns(): void
    {
        foreach ([Host::Theme, Host::Plugin] as $host) {
            $target = $this->generate($host);
            $result = (new GatesManifestCheck($target, $this->gatesManifest()))->examine();

            self::assertNotSame(Status::Fail, $result->status, $host->value.': '.$result->detail);
        }
    }

    /**
     * The plugin tree has never been generated by a test, which means every token
     * it holds is a token that survives into a customer's installation unwatched.
     * A theme's census protects nine repositories; a plugin's protects the same
     * trees nobody has ever looked inside.
     */
    public function testAGeneratedPluginCarriesNoScaffoldPresence(): void
    {
        $target = $this->generate(Host::Plugin);
        $survivors = [];

        foreach ($this->filesIn($target) as $relative) {
            $contents = (string) file_get_contents($target.'/'.$relative);

            foreach (['HOWDAH', 'Howdah', 'howdah', 'MAHOUT THEME NAME', 'Base Plugin'] as $token) {
                if (str_contains($contents, $token)) {
                    $survivors[] = $relative.' still carries '.$token;
                }
            }
        }

        self::assertSame([], $survivors, "tokens survived the generation:\n".implode("\n", $survivors));

        $composer = json_decode((string) file_get_contents($target.'/composer.json'), true, 512, JSON_THROW_ON_ERROR);
        self::assertSame('wordpress-plugin', $composer['type']);
        self::assertSame('iniznet/acceptance-plugin', $composer['name']);
        self::assertStringNotContainsString('scaffold', (string) json_encode($composer, JSON_THROW_ON_ERROR));

        // Core reads a plugin's name from the entry file, which is named after the
        // slug it is installed under.
        $header = (string) file_get_contents($target.'/'.Host::Plugin->identityFile('acceptance-plugin'));
        self::assertMatchesRegularExpression('/^ \* Plugin Name:\s*Acceptance Plugin\s*$/m', $header);
        self::assertStringContainsString('Text Domain: acceptance-plugin', $header);
    }

    private function generate(Host $host): string
    {
        return (new Scaffold())->generate(
            Host::Theme === $host ? 'acceptance-theme' : 'acceptance-plugin',
            $host,
            'native',
            'native',
            Host::Theme === $host ? 'classic' : null,
            null,
            $this->workingDirectory,
        )->target;
    }

    /**
     * @return list<string>
     */
    private function filesIn(string $root): array
    {
        $files = [];
        $iterator = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($root, \FilesystemIterator::SKIP_DOTS));

        foreach ($iterator as $item) {
            /** @var \SplFileInfo $item */
            if ($item->isFile()) {
                $path = str_replace('\\', '/', $item->getPathname());
                $files[] = substr($path, strlen(str_replace('\\', '/', $root)) + 1);
            }
        }

        sort($files);

        return $files;
    }

    private function packageRoot(): string
    {
        return dirname(__DIR__, 2);
    }

    /**
     * The manifest belongs to devtools, so devtools' own location answers for it. A
     * path read off the installed class survives a symlinked path repository, where
     * a sibling directory guessed from this package's position would not.
     */
    private function gatesManifest(): string
    {
        return dirname((new \ReflectionClass(GatesManifestCheck::class))->getFileName(), 4).'/resources/gates.json';
    }

    private function removeTree(string $target): void
    {
        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($target, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::CHILD_FIRST,
        );

        foreach ($iterator as $item) {
            $item->isDir() ? @rmdir($item->getPathname()) : @unlink($item->getPathname());
        }

        @rmdir($target);
    }
}
